### PR TITLE
Update version vllm

### PR DESCRIPTION
**Pull request by dimaioksha**

### CODE REVIEW

**Comment by youkaichao** [comment]
Well, this repo does not need to be updated very often :)

**Comment by dimaioksha** [comment]
> Well, this repo does not need to be updated very often :)

so should we close this pr or it can be merged?

**Comment by dtrifiro** [comment]
Hi @youkaichao, is there any particular reason for having this specific version of nccl installed? Why not just use the version installed as part of `nvidia-nccl-cu12` ?

**Comment by youkaichao** [comment]
see https://github.com/NVIDIA/nccl/issues/1234

**Pull request closed without merging**
